apiVersion: v1
kind: ConfigMap
metadata:
  name: pgcat-config
  namespace: dev
data:
  pgcat.toml: |
    [general]
    host = "0.0.0.0"
    port = 5432
    admin_username = "pgcat"
    admin_password = "pgcat"
    enable_prometheus_exporter = true
    prometheus_exporter_port = 9930
    log_level = "info"
    worker_threads = 4
    query_parser_enabled = true
    primary_reads_enabled = true
    healthcheck_timeout = 5000
    healthcheck_delay = 10000
    ban_time = 60
    server_tls = true
    server_tls_certificate_verification = false

    # --- catalogue ---
    [pools.catalogue]
    pool_mode = "transaction"
    default_role = "primary"
    application_name = "pgcat"
    query_parser_enabled = true
    query_parser_read_write_splitting = true
    primary_reads_enabled = true

    [pools.catalogue.users.formation]
    username = "formation"
    password = "test"
    pool_size = 10
    min_pool_size = 1
    server_lifetime = 300
    idle_timeout = 60

    [pools.catalogue.shards.0]
    database = "catalogue"
    servers = [
      ["postgres-primary.dev.svc.cluster.local", 5432, "primary"],
      ["postgres-0.postgres.dev.svc.cluster.local", 5432, "replica"],
      ["postgres-1.postgres.dev.svc.cluster.local", 5432, "replica"],
      ["postgres-2.postgres.dev.svc.cluster.local", 5432, "replica"]
    ]

    # --- order ---
    [pools.order]
    pool_mode = "transaction"
    default_role = "primary"
    application_name = "pgcat"
    query_parser_enabled = true
    query_parser_read_write_splitting = true
    primary_reads_enabled = true

    [pools.order.users.formation]
    username = "formation"
    password = "test"
    pool_size = 10
    min_pool_size = 1
    server_lifetime = 300
    idle_timeout = 60

    [pools.order.shards.0]
    database = "order"
    servers = [
      ["postgres-primary.dev.svc.cluster.local", 5432, "primary"],
      ["postgres-0.postgres.dev.svc.cluster.local", 5432, "replica"],
      ["postgres-1.postgres.dev.svc.cluster.local", 5432, "replica"],
      ["postgres-2.postgres.dev.svc.cluster.local", 5432, "replica"]
    ]

    # --- payment ---
    [pools.payment]
    pool_mode = "transaction"
    default_role = "primary"
    application_name = "pgcat"
    query_parser_enabled = true
    query_parser_read_write_splitting = true
    primary_reads_enabled = true

    [pools.payment.users.formation]
    username = "formation"
    password = "test"
    pool_size = 10
    min_pool_size = 1
    server_lifetime = 300
    idle_timeout = 60

    [pools.payment.shards.0]
    database = "payment"
    servers = [
      ["postgres-primary.dev.svc.cluster.local", 5432, "primary"],
      ["postgres-0.postgres.dev.svc.cluster.local", 5432, "replica"],
      ["postgres-1.postgres.dev.svc.cluster.local", 5432, "replica"],
      ["postgres-2.postgres.dev.svc.cluster.local", 5432, "replica"]
    ]
