apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-cpu-order
  namespace: dev
spec:
  mode: one
  selector:
    namespaces:
      - dev
    labelSelectors:
      app: order
  stressors:
    cpu:
      workers: 2
      load: 100
  duration: "5m"
