apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-chaos-mesh
  namespace: dev
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: chaos-mesh
