apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pgcat.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgcat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgcat.selectorLabels" . | nindent 8 }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "pgcat.selectorLabels" . | nindent 14 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "pgcat.selectorLabels" . | nindent 14 }}

      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: postgres
              containerPort: 5432
            - name: metrics
              containerPort: 9930

          volumeMounts:
            - name: config
              mountPath: /etc/pgcat/pgcat.toml
              subPath: pgcat.toml

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-config
