apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pgcat.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pgcat.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9930
      targetPort: 9930
