services:

  frontend:
    image: ${FRONTEND_IMAGE}:${FRONTEND_TAG}
    environment:
      CATALOG: $FRONTEND_CATALOG
      ORDERS: $FRONTEND_ORDERS
      PAYMENT: $FRONTEND_PAYMENT
      KEYCLOAK_URL: $FRONTEND_KEYCLOAK_URL
      KEYCLOAK_REALM: $FRONTEND_KEYCLOAK_REALM
      KEYCLOAK_CLIENT_ID: $FRONTEND_KEYCLOAK_CLIENT_ID
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/certs:/etc/nginx/certs:ro
    networks:
      - front

networks:
  front:
    driver: bridge