---
# NetworkPolicy — restreint le trafic réseau des pods PostgreSQL
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-netpol
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Trafic PostgreSQL depuis n'importe quel pod du namespace
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
    # Trafic Patroni entre les membres du cluster
    - from:
        - podSelector:
            matchLabels:
              {{- include "postgres.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8008

  egress:
    # Communication inter-pods PostgreSQL + Patroni
    - to:
        - podSelector:
            matchLabels:
              {{- include "postgres.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8008
    # DNS (résolution nécessaire pour Patroni / DCS)
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53