validationFailureAction: Audit

enforceNamespaces:
  - prod

excludeNamespaces:
  - kube-system
  - kyverno
  - argocd
  - ingress-nginx
  - sonarqube
  - calico-system
  - tigera-operator
  - argo-rollouts
  - vault
  - external-secrets

allowedRegistries:
  - "docker.io/library/*"
  - "docker.io/bitnami/*"
  - "ghcr.io/*"
  - "registry.k8s.io/*"
  - "quay.io/*"
  - "*.azurecr.io/*"

requiredLabels:
  - "app.kubernetes.io/name"
  - "app.kubernetes.io/managed-by"
