apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pg-backup
  namespace: postgres-backup
  annotations:
    # Remplir avec le client_id affiché par: terraform output -raw backup_identity_client_id
    azure.workload.identity/client-id: "7722596e-21b6-40e0-ae3f-934daa86907a"
  labels:
    azure.workload.identity/use: "true"
