apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgcat
  namespace: monitoring
  labels:
    app: pgcat
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: pgcat
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
