apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-annotations
  annotations:
    policies.kyverno.io/title: Add Default Annotations
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/description: >-
      Adds source managed-by annotation to Pods.
spec:
  rules:
    - name: add-default-annotations
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                {{- range .Values.excludeNamespaces }}
                - {{ . }}
                {{- end }}
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(deploy.kubernetes.io/source): "argocd"
