apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Images must come from approved registries only. This policy restricts
      container images to a predefined list of trusted registries.
spec:
  validationFailureAction: {{ .Values.validationFailureAction }}
  validationFailureActionOverrides:
    {{- range .Values.enforceNamespaces }}
    - action: Enforce
      namespaces:
        - {{ . }}
    {{- end }}
  rules:
    - name: restrict-image-registries
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                {{- range .Values.excludeNamespaces }}
                - {{ . }}
                {{- end }}
          - resources:
              annotations:
                sidecar.istio.io/status: "*"
      validate:
        message: "Images must come from an approved registry."
        foreach:
          - list: "request.object.spec.[initContainers, containers, ephemeralContainers][]"
            deny:
              conditions:
                all:
                  - key: "{{`{{element.image}}`}}"
                    operator: AnyNotIn
                    value:
                      {{- range .Values.allowedRegistries }}
                      - "{{ . }}"
                      {{- end }}
